name: 'Post Tweet V2 Action'
description: 'Post a tweet to Twitter during a GitHub Actions workflow with Twitter REST API for Version 2 endpoint..'
author: 'Julien SCHMITT'
inputs:
  message:
    description: 'The message ("tweet") to post to twitter.'
    required: true
  consumer-key:
    description: 'Consumer API key, available in the "Keys and tokens" section of your application in the Twitter Developer site.'
    required: true
  consumer-secret:
    description: 'Consumer API secret key, available in the "Keys and tokens" section of your application in the Twitter Developer site.'
    required: true
  access-token:
    description: 'Application access token, available in the "Keys and tokens" section of your application in the Twitter Developer site.'
    required: true
  access-token-secret:
    description: 'Application access token secret, available in the "Keys and tokens" section of your application in the Twitter Developer site.'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: edit
  color: blue