on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test a post to Twitter
    steps:
      - name: Hello world action step
        id: hello
        uses: noweh/post-tweet-v2-action@v0.9
        with:
          message: "Hi, this is a test!"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"