on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test a post to Twitter
    steps:
      - name: Hello world action step
        id: hello
        uses: noweh/post-tweet-v2-action@v0.2
        with:
          message: "Hi, this is a test!"
          bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"